CREATE TABLE IF NOT EXISTS service_health (
  ID BIGINT AUTO_INCREMENT,
  NAME VARCHAR(255),
  URL VARCHAR(255),
  STATUS VARCHAR(255),
  DATE_CREATED TIMESTAMP,
  LAST_UPDATED TIMESTAMP,
  PRIMARY KEY (ID)
);

ALTER TABLE service_health ADD CONSTRAINT service_health_url UNIQUE(URL);