version: '3.1'
services:
  db_mysql:
    image: mysql
    container_name: mysql
    restart: always
    environment:
      MYSQL_USER: mysql_user
      MYSQL_PASSWORD: user_password
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: service_health_db
    ports:
      - "3306:3306"
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    restart: always
    container_name: php_myadmin
    depends_on:
      - db_mysql
    environment:
      PMA_HOST: db_mysql
      PMA_USER: root
      PMA_PASSWORD: root_password
    ports:
      - "8085:80"