server:
  port: 8081
  servlet:
    context-path: /service-provider

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/service_health_db
    username: mysql_user
    password: user_password
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect

  flyway:
    url: jdbc:mysql://localhost:3306/service_health_db
    user: mysql_user
    password: user_password
    locations: classpath:/db/migration

service:
  client:
    timeout:
      read: 2s
      connect: 2s

logging:
  level:
    com:
      example:
        poller: DEBUG